services:

    blog:
      build: . 
      container_name: blog  
      restart: always
      command: bash entrypoint.sh
      volumes:
        - .:/app
        - static:/app/static
        - media:/app/media
      env_file:
        - .env
      depends_on:
        - redis_blog  
        
    redis_blog:
      image: redis:7.0-bookworm
      container_name: redis_blog  
      restart: always

    nginx_blog:
      build: ./nginx
      container_name: "nginx_blog"
      restart: always
      volumes:
        - static:/app/static
        - media:/app/media
      ports:
        - 8001:80
      depends_on:
        - blog  


volumes:
  static:    
  media: