# Generated by Django 3.2 on 2023-01-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_time', 'updated_time']},
        ),
    ]
