# Generated by Django 4.1.6 on 2023-02-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
    ]
