# Generated by Django 3.2 on 2023-07-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_time',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
